export {default as BackTracking} from "agorithm/pages/BackTracking"
export {default as BruteForce} from "agorithm/pages/BruteForce"
export {default as DivideConquer} from "agorithm/pages/DivideConquer"
export {default as DynamicProgramming} from "agorithm/pages/DynamicProgramming"
export {default as Greedy} from "agorithm/pages/Greedy"