# Generated by Django 3.2.5 on 2021-10-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uservo',
            table='users',
        ),
    ]
