# Generated by Django 3.2.5 on 2021-10-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_uservo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservo',
            name='email',
            field=models.TextField(),
        ),
    ]
